// Generated by gencpp from file erp42_msgs/Utm.msg
// DO NOT EDIT!


#ifndef ERP42_MSGS_MESSAGE_UTM_H
#define ERP42_MSGS_MESSAGE_UTM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erp42_msgs
{
template <class ContainerAllocator>
struct Utm_
{
  typedef Utm_<ContainerAllocator> Type;

  Utm_()
    : x(0.0)
    , y(0.0)
    , heading(0.0)  {
    }
  Utm_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::erp42_msgs::Utm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erp42_msgs::Utm_<ContainerAllocator> const> ConstPtr;

}; // struct Utm_

typedef ::erp42_msgs::Utm_<std::allocator<void> > Utm;

typedef boost::shared_ptr< ::erp42_msgs::Utm > UtmPtr;
typedef boost::shared_ptr< ::erp42_msgs::Utm const> UtmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erp42_msgs::Utm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erp42_msgs::Utm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::erp42_msgs::Utm_<ContainerAllocator1> & lhs, const ::erp42_msgs::Utm_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::erp42_msgs::Utm_<ContainerAllocator1> & lhs, const ::erp42_msgs::Utm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace erp42_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::erp42_msgs::Utm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erp42_msgs::Utm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erp42_msgs::Utm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erp42_msgs::Utm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erp42_msgs::Utm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erp42_msgs::Utm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erp42_msgs::Utm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5833e31792a7e4dcbebcee30b7c23de8";
  }

  static const char* value(const ::erp42_msgs::Utm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5833e31792a7e4dcULL;
  static const uint64_t static_value2 = 0xbebcee30b7c23de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::erp42_msgs::Utm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erp42_msgs/Utm";
  }

  static const char* value(const ::erp42_msgs::Utm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erp42_msgs::Utm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 heading\n"
;
  }

  static const char* value(const ::erp42_msgs::Utm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erp42_msgs::Utm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Utm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erp42_msgs::Utm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erp42_msgs::Utm_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERP42_MSGS_MESSAGE_UTM_H
